### ISSUE TITLE
[bug] QueryTask doesn't respect the current query scope and overwrite everything till the end of the buffer

### ISSUE THREAD

**Issue by huantrinh1802** [huantrinh1802/m_taskwarrior_d.nvim#39]

**Comment by simonlearnscoding** [comment]
It should be an easy fix by checking if the line starts with # which will indicate that its a new md title and stop there. I can have a look at it if you want or otherwise let me know when I can pull. 

also do you think it would be feasible to merge the TWSyncTasks and TWQueryTasks?

I mean TWSyncTasks would run TWSyncTasks for the whole buffer and add every query it finds in an array with the line number, then after it synced, for every query it found it will go to that query and run the TWQueryTasks command there

**Comment by huantrinh1802** [comment]
The PR #41 fixed this. I am running manual tests before merging it.

There are a few reasons why I don't want to have TWSyncTasks and TWQueryTasks as one:

- TWSyncTasks will look for tasks and either create/sync the task to Taskwarrior (including detecting nesting tasks/dependent tasks). This heavily relies on lines and line number in the buffer
- Meanwhile, TWQueryTasks will blow up everything in the scope (between two empty lines aka a paragraph in Neovim/Vim/TreeSitter). This destroy any references of the lines in the buffer, thus useless for TWSyncTasks

Happy to open to new ideas but I cannot see how would I merge these commands.

**Comment by simonlearnscoding** [comment]
I think one would have to happen after the other, so first twsynctasks would create and sync, then after that twquery would blow up and recreate to make sure its up to date with the query but yeah its probably just personal preference
